services:
   proxy:
      image: proxy:1.0
      links:
         - identidock
      ports:
         - "80:80"
      environment:
         - NGINX_HOST=192.168.30.53
         - NGINX_PROXY=http://identidock:9090
      profiles: ["${PROFILE:-prod}"]

   identidock:
      extends:
         file: common.yml
         service: identidock 
      ports:
         - "5000:5000"
      environment:
         ENV: PROD

   dnmonster:
      extends:
         file: common.yml
         service: dnmonster

   redis:
      extends:
         file: common.yml
         service: redis

