services:
    proxy:
       image: proxy:1.0
       links:
          - identidock
       ports:
          - "80:80"
       environment:
          - NGINX_HOST=192.168.30.53
          - NGINX_PROXY=http://identidock:9090
       deploy:
          resources:
             limits:
                memory: 128M
             reservations:
                memory: 64M    
    
    identidock:
       extends:
          file: common.yml
          service: identidock
       environment:
          ENV: PROD
       deploy:
          resources:
             limits:
                memory: 256M
             reservations:
                memory: 64M

    dnmonster:
       extends:
          file: common.yml
          service: dnmonster 
       deploy:
         resources:
            limits:
               memory: 128M
            reservations:
               memory: 64M

    redis:
       extends:
          file: common.yml
          service: redis
       deploy:
          resources:
             limits:
                memory: 128M
             reservations:
                memory: 64M

