services:
   identidock:
      build: .
      container_name: identidock
      expose:
         - "9090"
      environment:
         ENV: PROD
      links:
         - dnmonster
         - redis

   dnmonster:
      image: amouat/dnmonster:1.0
      container_name: dnmonster

   redis:
      image: redis:8.6.2-alpine
      container_name: redis

