input {
   tcp {
      port => 5000
      codec => json
   }

   udp {
      port => 5000
      codec => json
   }
}

filter {

   if [message] !~ /(GET|POST|Cache miss|From cache)/ {
      drop { }
   }

   if [message] =~ /^\[pid:/ {
      drop { }
   }

   if [event.original] =~ /(GET|POST)/ {
      mutate { 
         replace => {type => "nginx"} 
      }

      grok {
	 match => { "event.original" => "%{COMBINEDAPACHELOG}" }
      }

      mutate {
         convert => [ "response", "integer" ]
         convert => [ "bytes", "integer" ]
      }
   }

   if [message] =~ /(Cache miss|From cache)/ {
      mutate {
         replace => { "type" => "app" }
      }
   }
}


output {
   elasticsearch { hosts => "elasticsearch" }
}
